version: '3.7'
services:
    sffs:
        image: soundflow/sffs:latest
        container_name: sffs
        volumes:
            - './sfdata:/sfdata'
        ports:
            - '80:1795'
            - '1790:1790'
        restart: always
